repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        additional_dependencies: ['gibberish-detector']
        exclude: package.lock.json
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.37.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@8.36.0
-   repo: local
    hooks:
    -   id: pre-build
        name: yarn build
        entry: bash -c "yarn build"
        language: system
        files: package.json
        stages: [commit]
        pass_filenames: false
        verbose: true
        always_run: true
