name: Deploy PR to Firebase Release Channel

on:
  pull_request:
    branches:
      - staging
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: yarn install
    - run: yarn build

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Preview Channel
      id: deploy
      run: |
        PR_NUMBER=${{ github.event.number }}
        npx firebase hosting:channel:deploy pr-${PR_NUMBER} --only functions,hosting --token "$FIREBASE_TOKEN" | tee deploy.log
        URL=$(cat "deploy.log" | grep -o 'https://[^[:space:]]*')
        echo "::set-output name=url::$URL"

    - name: Add comment to PR
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = ${{ github.event.number }};
          const previewUrl = '${{ steps.deploy.outputs.url }}';
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: `🚀 Deployment to preview channel successful!\n\nPreview URL: [${previewUrl}](${previewUrl})`
          });
